### ISSUE TITLE
Error in visualize_nonlinear_causal_effect

### ISSUE THREAD

**Issue by hendriklohse** [cdt15/lingam#140]
The [example ](https://lingam.readthedocs.io/en/latest/tutorial/visualize_nonlinear_causal_effect.html) of `utils.visualize_nonlinear_causal_effect` does not seem to work anymore. 

When running it, you get a problem with the shape of `cd_result`. The error occurs at `_is_adjacency_matrix(cd_result, X.shape[1])` and is caused by `check_array(cd_result)`. It yields `ValueError: Expected 2D array, got scalar array instead`. 

How can this be fixed?

**Comment by ikeuchi-screen** [comment]
Hi @hendriklohse ,
I did not get any errors with the example code in my environment.
Are you setting the bootstrap result in the argument **bs_result**?
```python
fig = visualize_nonlinear_causal_effect(X, bs_result, RandomForestRegressor(), "X2", "X3", fig=fig)
```
