### ISSUE TITLE
Prior Knowledge LongitudinalLiNGAM

### ISSUE THREAD

**Issue by Francesco-Canonaco** [cdt15/lingam#148]
Is it prior knowledge available for LongitudinalLiNGAM?

**Comment by sshimizu2006** [comment]
Not yet, but we are planning to implement that.

**Comment by Francesco-Canonaco** [comment]
Thank you 👍

**Comment by sshimizu2006** [comment]
Now, the option prior knowledge for LongitudinalLiNGAM is available (version 1.9.1).
