### ISSUE TITLE
[bug] pip installation issue - statsmodels dependency not recognized

### ISSUE THREAD

**Issue by el-hult** [cdt15/lingam#22]
when installing via pip and PyPI, the statsmodels dependency is not installed. Is is listed as a dependency in the readme, but it is not identified by PyPI. I guess it is because it is also missing from `setup.py`. 

I guess this counts as a bug....

also - installing statsmodels manually solves it, so it is not that bad....

**Comment by ikeuchi-screen** [comment]
Thanks for reporting this problem. I'll fix this bug in the next version, v1.5.2.
