### ISSUE TITLE
Interpretation 

### ISSUE THREAD

**Issue by carterrees** [cdt15/lingam#30]
The code and documentation is fantastic. But how about some interpretation of the outputs in relation to the examples. What can and cannot be said about the coefficients, adjacency matrices etc?

**Comment by sshimizu2006** [comment]
Hi, for example, the code package uses bootstrapping to evaluate the significance of the coefficients b_{ij} in the adjacency matrix B = [b_{ij}]. The coefficients b_{ij} represent the magnitudes of the direct causal effects from variable x_j to x_i.
