### ISSUE TITLE
Prior adjancency matrices

### ISSUE THREAD

**Issue by fccoelho** [cdt15/lingam#4]
Why are prior adjacency matrices, created  with the `make_prior_knowledge` function,  have -1 for the edges instead of 1? what is the rationale for this?

**Comment by ikeuchi-screen** [comment]
In `make_prior_knowledge`, the edge that no prior knowledge is given is -1.

Prior knowledge is defined as the following [[ref]](http://www.jmlr.org/papers/volume12/shimizu11a/shimizu11a.pdf):
* 0 if xi does not have a directed path to xj
* 1 if xi has a directed path to xj
* −1 if no prior knowledge is available to know if either of the two cases above (0 or 1) is true.

The above explanation is missing in the API reference and tutorials, so it will be added in the next version.

**Comment by fccoelho** [comment]
I was guessing that was what it meant. Thanks for the clarification.
BTW, thanks for putting this package together!
