### ISSUE TITLE
About discrete graphs

### ISSUE THREAD

**Issue by caimingA** [cdt15/lingam#68]
Hello,

This is the second time I ask a question. Thanks for your wonderful work.

When we use the OLS linear regression method, we can't get 0 even if there is no edge between two variable nodes. So, in your work instead of the general linear regression, the adaptive Lasso is used.

However, for some data, even with the adaptive Lasso, there are times when it can not guarantee that the DirectLiNGAM result will not have redundant edges, even though the values of the edges are very close to zero.

I think if I can further prune the adjacency matrix, the result might be closer to the true matrix. But, I don't know what criteria should I use for pruning, especially when analyzing discrete graphs in which there is no edge.

I'm wondering if I can directly get an answer here or if you can recommend me some papers that will be helpful.

**Comment by sshimizu2006** [comment]
One way to strengthen the sparseness would be to use a different gamma, probably a bigger gamma, maybe 2 http://users.stat.umn.edu/~zouxx019/Papers/adalasso.pdf
Now it's 1.0.
https://lingam.readthedocs.io/en/latest/_modules/lingam/utils.html#predict_adaptive_lasso

**Comment by caimingA** [comment]
Thanks for your kind reply.

I think using a bigger gamma can literally improve the strength of the sparseness. I will have a try.

And, I'm wondering if there is a method that can prune edges after outputting the adjacency matrix by DirectLiNGAM.  For example, when I did a simulation, my coefficient matrix B followed `U[-1, -0.5] ∪ U[0.5, 1]`. Then I can cut edges if the values were greater than -0.25 and less than 0.25 (this indeed simply improved the simulation results). But, I can not know the true distribution if I want to analyze real-world data. 

Are there criteria or something else if I want to prune edges like this?

Thanks

**Comment by sshimizu2006** [comment]
Well, drawing the histogram of coefficients computed using bootstrap might help.
https://lingam.readthedocs.io/en/latest/tutorial/bootstrap.html

**Comment by caimingA** [comment]
Thanks!

I think this will work. I'm going to study it in detail.

Have a nice one!
