### ISSUE TITLE
Questions about usage of DirectLiNGAM

### ISSUE THREAD

**Issue by soya-beancurd** [cdt15/lingam#78]
Hello, I’d first like to thank you for this incredible package (along with the interesting papers on LiNGAM you’ve published)!

I’m currently trying to employ this package in my Causal Inference pipeline (causal discovery portion). 
- I’m currently trying to measure the treatment effects of a binary treatment on a binary outcome, in the presence of hundreds of potential confounders
- At present, I am trying to first identify a causal graph using this package for relatively large datasets before identifying confounders using dowhy’s Backdoor Criterion and estimating treatment effects using EconML’s methods.
- The datasets have sizes ranging about ~250k - 750k rows/entries and 150 - 600+ columns/features

More specifically, I am currently using DirectLiNGAM with a prior knowledge matrix (specifically for having an edge from the treatment to outcome variable, and that there should be no other outgoing edges from both the treatment and outcome variables). *BottomUpParceLiNGAM would have been the ideal model but it dosent work due to scalability and instant out of memory issues.*

After running a couple of experiments with DirectLiNGAM, I have 3 questions I’d like to clarify with you if possible:

1. (Extension of [Issue 5](https://github.com/cdt15/lingam/issues/5)) As my dataset has a good mix of continuous and discrete data, are there currently any models in the package that can deal with both continuous and discrete (i.e, binary and encoded categorical) variables, ***while*** allowing for prior knowledge matrices?
2. Are there any scalable alternatives to validate the results and assumptions of LiNGAM models in general aside from `get_error_independence_p_values` and `bootstrap`? As the former (specifically during `hsic_test_gamma`) causes out of memory issues for even the smallest dataset (e.g., *250k x 155*), while the latter takes too long (i.e, the default `fit` in DirectLiNGAM with the above mentioned prior-knowledge matrix ranges between 20 hours - 5 days for the datasets I currently have)
3. It seems that regardless of the dataset, DirectLiNGAM *consistently* outputs a causal graph (adjacency matrix) where all the non-outcome & non-treatment features are considered confounders (via Backdoor Criterion from dowhy). This is different when compared to using ICALiNGAM which does not necessarily produce results with such a trend. Could it be due to the way in which DirectLiNGAM tries to identify the causal order (and therefore the adjacency matrix)?

Thank you very much!

**Comment by sshimizu2006** [comment]
p.s. It would be better to use a different method, e.g., something implemented in dowhy, to compute causal effects from your continuous variables on the binary treatment rather than using the output of DirectLiNGAM. DirectLiNGAM assumes all the variables are continuous when it computes the causal effects.

**Comment by sshimizu2006** [comment]
Ok, then, the direct edges from the continous variables to the binary treatment might not be properly pruned. DirectLiNGAM uses sparse linear regression to prune directed edges assuming all the variables are continous. Some other methods like sparse logistic regression having the continuous variables as explanatory variables and the treatment as the response variable would be better to estimate existence of directed edges from those continous variables on the binary treatment (and outcome), though DirectLiNGAM can estimate the causal structure of the continuous variables.

**Comment by sshimizu2006** [comment]
My suggestion would be something like
0. Remove all binary variables, apart from the treatment (T) and outcome (Y)
1. Run DirectLiNGAM on all the continuous variables to get a causal graph of the continuous variables.
2 and 3. Adaptive logistic regression (4.1 of the original adaptive lasso paper: http://users.stat.umn.edu/~zouxx019/Papers/adalasso.pdf) having all the continuous variables as the features and binary treatment as the target. Do the same for the binary outcome. Draw directed edges from the continous variables to the treatment and target based on the sparse patterns of the sparse logistic regression coefficients.
4. Give the causal graph of the continuous variables, binary treatment and outcome to doWhy.

![IMG_9019](https://user-images.githubusercontent.com/11813160/220829416-47186176-f804-48e8-b358-57d957667325.jpg)

**Comment by sshimizu2006** [comment]
Hi, 

DirectLiNGAM tries to find a DAG that minimizes dependence between error terms. DirectLiNGAM does not use HSIC to prune edges. Rather, HSIC is used to see if the error terms in the estimated DAG are independent. Thiis is to find possible violations of the independence assumption.

**Comment by sshimizu2006** [comment]
Yeah, that could be an alternative way for pruning edges.
