### ISSUE TITLE
Test Error: ValueError: 'x0' must only have one dimension.

### ISSUE THREAD

**Issue by ikeuchi-screen** [cdt15/lingam#93]
I get the following error when I run the lina.py test.

```python
FAILED tests/test_lina.py::test_fit_lina - ValueError: 'x0' must only have one dimension.
FAILED tests/test_lina.py::test_fit_mdlina - ValueError: 'x0' must only have one dimension.
```

The following changes in scipy-1.11.0 may have affected this.

[SciPy 1.11.0 Release Notes](https://scipy.github.io/devdocs/release/1.11.0-notes.html)

* The [scipy.optimize.minimize](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) function now raises an error for x0 with x0.ndim > 1.

**Comment by ikeuchi-screen** [comment]
`factor_analyzer` used in `lina.py` is using `scipy.minimize`.

```python
lingam/lina.py:316: in fit
    cfa.fit(X, G_sign)
/usr/local/lib/python3.10/site-packages/factor_analyzer/confirmatory_factor_analyzer.py:742: in fit
    res = minimize(
```

**Comment by ikeuchi-screen** [comment]
@YanaZeng 
I don't understand the LiNA algorithm very well.
As mentioned above, it may be a problem with the factor_analyzer library.
Do you know how we can solve this problem?

**Comment by ikeuchi-screen** [comment]
Hi, @YanaZeng 
Thank you for your confirmation!
I believe this is caused by a change in scipy-1.11.0, as mentioned in my opening post.

The test code execution resulted in the following `x0` values.
In this form, it is a **2d** vector.
```python
x0 = array([[1.  ],
       [1.  ],
       [0.  ],
       [0.  ],
       [0.  ],
       [0.  ],
       [0.  ],
       [0.  ]...      [0.05],
       [0.05],
       [0.05],
       [0.05],
       [0.05],
       [0.05],
       [0.05],
       [0.05]])
```

The results of the test code execution can be found at the following link:
https://github.com/cdt15/lingam/actions/runs/5376105848/jobs/9752810059#step:6:155

**Comment by ikeuchi-screen** [comment]
@YanaZeng 
I have made a pull request to `factor_analyzer` GitHub on how to fix this problem.
https://github.com/EducationalTestingService/factor_analyzer/pull/123

However, I don't think it will be merged for a while, so I will fix it so that the LiNA test will not run.

**Comment by YanaZeng** [comment]
Get it, Ikeuchi-san! お疲れ様でした.

**Comment by ikeuchi-screen** [comment]
I close this issue because the PullRequest for factor_analyzer has been merged.
https://github.com/EducationalTestingService/factor_analyzer/pull/124
